import React, { Component } from "react";
import { Link } from "react-router-dom";

import Button from "@material-ui/core/Button";
import Grid from "@material-ui/core/Grid";
import Typography  from "@material-ui/core/Typography";
import FormHelperText from "@material-ui/core/FormHelperText";
import FormControl from "@material-ui/core/FormControl";
import Radio from "@material-ui/core/Radio"
import RadioGroup  from "@material-ui/core/RadioGroup";
import FormControlLabel from "@material-ui/core/FormControlLabel";

export default class StartGamePage extends Component {

    constructor(props) {
        super(props);
        this.state = {
            cards_id: "1",
            marker_id: "1"
        };

        this.handleStartButtonPressed = this.handleStartButtonPressed.bind(this);
        this.handleCardThemeChange = this.handleCardThemeChange.bind(this);
        this.handleMarkerChange = this.handleMarkerChange.bind(this);
    }

    handleCardThemeChange(e) {
        this.setState({
            cards_id: e.target.value,
        });
    }

    handleMarkerChange(e) {
        this.setState({
            marker_id: e.target.value,
        });
    }

    handleStartButtonPressed() {
        const requestOptions = {
            method: "POST",
            headers: {"Content-Type": "application/json"},
            body: JSON.stringify({
                cards_id: this.state.cards_id,
                marker_id: this.state.marker_id,
            }),
        };
        fetch("/api/create_game", requestOptions)
        .then((response) => response.json())
        .then((data) => console.log(data));
    }

    render() {
        return (<Grid container spacing={1}>
            <Grid item xs={12} align="center">
                <Typography component="h4" variant="h4">
                    Start a Game.
                </Typography>
            </Grid>
            <Grid item xs={12} align="center">
                    <FormControl component="fieldset">
                        <FormHelperText>
                            <div align="center">
                                Select Card Pack
                            </div>
                        </FormHelperText>
                        {/* add code so that a formcontrol label is generated by the available card packs for now hard coded values */}
                        <RadioGroup row defaultValue="true" onChange={this.handleCardThemeChange}>
                            <FormControlLabel value="1" control={<Radio color="primary"/>}
                                                           label="Traditional"
                                                           labelPlacement="bottom"
                            />
                            <FormControlLabel value="2" control={<Radio color="primary"/>}
                                                           label="Special"
                                                           labelPlacement="bottom"
                            />
                            <FormControlLabel value="3" control={<Radio color="primary"/>}
                                                           label="Other Special"
                                                           labelPlacement="bottom"
                            />
                        </RadioGroup>
                    </FormControl>
            </Grid>
            <Grid item xs={12} align="center">
            <FormControl component="fieldset">
                        <FormHelperText>
                            <div align="center">
                                Select Markers:
                            </div>
                        </FormHelperText>
                        {/* add code so that a formcontrol label is generated by the available card packs for now hard coded values */}
                        <RadioGroup row defaultValue="true" onChange={this.handleMarkerChange}>
                            <FormControlLabel value="1" control={<Radio color="primary"/>}
                                                           label="Plastic Dots"
                                                           labelPlacement="bottom"
                            />
                            <FormControlLabel value="2" control={<Radio color="primary"/>}
                                                           label="Quarters"
                                                           labelPlacement="bottom"
                            />
                            <FormControlLabel value="3" control={<Radio color="primary"/>}
                                                           label="Beans"
                                                           labelPlacement="bottom"
                            />
                        </RadioGroup>
                    </FormControl>    
            </Grid>
            <Grid item xs={12} align="center">
                <Button color="primary" variant="contained" onClick={this.handleStartButtonPressed}>
                    Start Game
                </Button>
            </Grid>
            <Grid item xs={12} align="center">
                <Button color="secondary" variant="contained" to="/" component={ Link }>
                    Back
                </Button>
            </Grid>
        </Grid>
        );
    }
}